### ISSUE TITLE
Support Crystal 1.0?

### ISSUE THREAD

**Issue by kojix2** [elorest/bitfields#8]
Hi bitfields developers.

Thank you for creating useful package.
When I try to install shards, I get the following error message.

```
Unable to satisfy the following requirements:

- `crystal (~> 0.27, >= 0.27.0)` required by `bitfields 0.2.2`
Failed to resolve dependencies, try updating incompatible shards or use --ignore-crystal-version as a workaround if no update is available.
```

It would be great if you could support 1.0.

**Comment by kojix2** [comment]
I ran the test.
`crystal spec/bitfields_spec.cr `

```
........................

Finished in 967 microseconds
24 examples, 0 failures, 0 errors, 0 pending
```

All tests seem to have passed. :+1:

**Comment by elorest** [comment]
Thanks. I'm fixing this now. So many deps to keep up to date lol.

**Comment by kojix2** [comment]
Thank you!

I'm trying to create a binding for a C library that contains bitfields. I think this package will be very useful.
It would be even better if [crystal_lib could support bitfields](https://github.com/crystal-lang/crystal_lib/issues/76).

**Comment by elorest** [comment]
I agree. If your interested in a mix of big and little endian values checkout my crystal conf talk on binary messaging. I linked to another example project in there.
